### PR TITLE
Update Screenshots enabling addon for Balrog-driven rollout

### PR DESCRIPTION
**Pull request by 6a68**
See https://bugzilla.mozilla.org/show_bug.cgi?id=1389584

### CODE REVIEW

**Comment by 6a68** [comment]
Hmm, looks like the linter fails on node 6.x, but it's fine on 8.x. 

Also seems ok if I roll back the `eslint-plugin-mozilla` version from 0.4.2 to 0.4.0.

**Comment by 6a68** [comment]
Ah, I'm out of time for today for this issue, and haven't figured out quite what's going on.

@Standard8, would you mind taking a look at the linter errors here? The lint test passes on node 8.x, but is busted on node 6.x, which is the version used by taskcluster. The error is rather non-informative: 

```sh
> one-off-system-add-ons@0.0.1 lint /Users/jhirsch/codez/github/mozilla-one-off-system-add-ons
> eslint --ext=.js,.json .


/Users/jhirsch/codez/github/mozilla-one-off-system-add-ons/.eslintrc.js
  0:0  error  Parsing error: Cannot read property 'ecmaFeatures' of undefined

/Users/jhirsch/codez/github/mozilla-one-off-system-add-ons/addons/asyncrendering/bootstrap.js
  0:0  error  Parsing error: Cannot read property 'ecmaFeatures' of undefined

/Users/jhirsch/codez/github/mozilla-one-off-system-add-ons/addons/aushelper/bootstrap.js


"use strict";
  0:0  error  Parsing error: Cannot read property 'ecmaFeatures' of undefined

/Users/jhirsch/codez/github/mozilla-one-off-system-add-ons/addons/disable-captive-portal/bootstrap.js
  0:0  error  Parsing error: Cannot read property 'ecmaFeatures' of undefined

/Users/jhirsch/codez/github/mozilla-one-off-system-add-ons/addons/disable-cert-transparency/bootstrap.js
  0:0  error  Parsing error: Cannot read property 'ecmaFeatures' of undefined

/Users/jhirsch/codez/github/mozilla-one-off-system-add-ons/addons/disable-prefetch/bootstrap.js
  0:0  error  Parsing error: Cannot read property 'ecmaFeatures' of undefined

/Users/jhirsch/codez/github/mozilla-one-off-system-add-ons/addons/enable-screenshots/bootstrap.js
  0:0  error  Parsing error: Cannot read property 'ecmaFeatures' of undefined

/Users/jhirsch/codez/github/mozilla-one-off-system-add-ons/addons/hsts-priming/bootstrap.js
  0:0  error  Parsing error: Cannot read property 'ecmaFeatures' of undefined

/Users/jhirsch/codez/github/mozilla-one-off-system-add-ons/addons/outofdate-notifications/bootstrap.js
  0:0  error  Parsing error: Cannot read property 'ecmaFeatures' of undefined

/Users/jhirsch/codez/github/mozilla-one-off-system-add-ons/addons/tls13-comparison-v1/bootstrap.js
  0:0  error  Parsing error: Cannot read property 'ecmaFeatures' of undefined

/Users/jhirsch/codez/github/mozilla-one-off-system-add-ons/addons/tls13-compat-ff51/bootstrap.js
  0:0  error  Parsing error: Cannot read property 'ecmaFeatures' of undefined

/Users/jhirsch/codez/github/mozilla-one-off-system-add-ons/addons/tls13-compat-ff51/test/browser_check_installed.js
  0:0  error  Parsing error: Cannot read property 'ecmaFeatures' of undefined

/Users/jhirsch/codez/github/mozilla-one-off-system-add-ons/addons/tls13-compat-ff51/test/browser_test_tls_setting.js
  0:0  error  Parsing error: Cannot read property 'ecmaFeatures' of undefined

/Users/jhirsch/codez/github/mozilla-one-off-system-add-ons/addons/websensehelper/bootstrap.js
  0:0  error  Parsing error: Cannot read property 'ecmaFeatures' of undefined

/Users/jhirsch/codez/github/mozilla-one-off-system-add-ons/testing/mochitest/browser.eslintrc.js
  0:0  error  Parsing error: Cannot read property 'ecmaFeatures' of undefined

✖ 15 problems (15 errors, 0 warnings)
```

The errors are fixed if I remove the `addons/tls13-compat-ff51/test/.eslintrc.js` file, then edit the main `.eslintrc.js` to remove `mozilla` from `plugins`, and `plugin:mozilla/recommended` from `extends`.

What's funny is that I tried inlining the mozilla/recommended eslint rules, and that didn't introduce any errors. I took the rules from [here](https://hg.mozilla.org/mozilla-central/raw-file/5322c03f4c8587fe526172d3f87160031faa6d75/tools/lint/eslint/eslint-plugin-mozilla/lib/configs/recommended.js), are they up to date with the `mozilla-recommended` plugin?

Suggestions welcome :-)

**Comment by 6a68** [comment]
Gijs suggested just bumping the node version to 8.x here, might look into that next

**Comment by 6a68** [comment]
Bumping the node version would require tweaking the taskcluster config file to use a different node version. Looks like the image used by taskcluster isn't an off-the-shelf node.js image, but a custom image called [standard8/one-off-system-add-ons.2017030801.800ba54a4bd5](https://github.com/mozilla/one-off-system-add-ons/blob/master/.taskcluster.yml#L18).

Not sure what else to do here, for now.

**Comment by 6a68** [comment]
By the power of [managerial fiat](http://logs.glob.uno/?c=mozilla%23screenshots&s=14+Aug+2017&e=14+Aug+2017#c21284), I'm going to use my github superpowers to temporarily disable the requirement that the linter pass (Settings > Branches > Branch protection for master > " Require status checks to pass before merging" checkbox), then I'm going to land this PR. I'll open a followup bug to re-enable the test passing requirement after the image is updated.

**Comment by rhelmer** [comment]
Thanks @6a68 - honestly this seems like a lot of work to me just to do a lint. I wonder if we could more easily hook GH up to tryserver, instead of having to set up a special TC build...

**Comment by 6a68** [comment]
yeah, great idea

**Pull request merged**
