### PR TITLE
Search remediation

### PR DESCRIPTION
**Pull request by mkaply**
This is a one-off system add-on for remediating search back to Firefox 45.

### CODE REVIEW

**Comment by rhelmer** [comment]
@mkaply can you please resolve the lint problems in https://tools.taskcluster.net/groups/AZZHVCy7T6OKIRQzh5wZKw/tasks/AZZHVCy7T6OKIRQzh5wZKw/runs/0/logs/public%2Flogs%2Flive.log so we can merge? Thanks!

**Comment by mkaply** [comment]
Are these rules not the same as mozilla-central? It appears you don't allow dangling commas?

Note this is designed to run on older Firefoxes, so most of these errors don't apply. I'll add the appropriate lint workaround.

**Comment by rhelmer** [comment]
@mkaply the idea is that the rules are supposed to be the same (which is why we use taskcluster etc) but @Standard8 set this up so I'll ask him to confirm.

Agreed on making this work for older firefoxen - I tend to just use eslint ignore comments for those cases.

**Comment by Standard8** [comment]
Oh blast, it is in the top level `.eslintrc.js`. As are a lot of other rules... not sure why that is, I'll try and grab some time soon to clean this up a bit.

**Pull request merged**
