### PR TITLE
Bug 1368433 - pref flip add-on to disable ocsp stapling

### PR DESCRIPTION
**Pull request by rhelmer**

### CODE REVIEW

**Comment by rhelmer** [comment]
r=felipe per IRC

**Comment by Standard8** [comment]
@rhelmer This seems similar to @ekr's #44 PR although the code is different, also the tests are failing.

Which one should we be taking?

**Comment by ekr** [comment]
Don't take either. This has been overtaken by evnets.

**Comment by Standard8** [comment]
Thanks, I'll close them out.

**Pull request closed without merging**
